import Head from 'next/head'
import Navbar from '../components/Navbar'
import DedNav from '../components/Navbar/dednav'
import Section from "../components/Section/index"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Boomerang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
       <div className=''>
        <DedNav/>
        <Navbar/>
        <Section/>
       </div>
    </div>
  )
}
